"""Fill official tax forms.

Two paths:
1. **AcroForm fill** via ``pypdf.PdfWriter.update_page_form_field_values`` when a
   fillable template + fieldmap YAML exist under
   ``templates/forms/<jurisdiction>/<year>/<form_code>.pdf`` and ``.fieldmap.yaml``.
2. **Overlay fallback** via ``reportlab`` when a ``<form_code>.coordmap.yaml``
   exists but the AcroForm fields are missing or flattened.

When neither template exists we emit a plain-text "draft form" PDF so the
pipeline always produces something downloadable.
"""

from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

TEMPLATES_ROOT = Path(__file__).resolve().parent.parent / "templates" / "forms"


def _template_paths(jurisdiction: str, year: int, form_code: str) -> Dict[str, Path]:
    base = TEMPLATES_ROOT / jurisdiction.lower() / str(year)
    safe_code = form_code.replace("/", "_")
    return {
        "pdf": base / f"{safe_code}.pdf",
        "fieldmap": base / f"{safe_code}.fieldmap.yaml",
        "coordmap": base / f"{safe_code}.coordmap.yaml",
    }


def _load_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _acroform_fill(template_pdf: Path, fieldmap: Dict[str, Any], values: Dict[str, Any]) -> Optional[bytes]:
    try:
        from pypdf import PdfReader, PdfWriter
    except Exception:
        return None
    try:
        reader = PdfReader(str(template_pdf))
        writer = PdfWriter(clone_from=reader)
        mapped: Dict[str, str] = {}
        for engine_key, pdf_field in fieldmap.items():
            if engine_key in values and values[engine_key] is not None:
                mapped[pdf_field] = f"{values[engine_key]}"
        if not mapped:
            return None
        for page in writer.pages:
            writer.update_page_form_field_values(page, mapped)
        buf = BytesIO()
        writer.write(buf)
        return buf.getvalue()
    except Exception:
        return None


def _text_overlay_fill(template_pdf: Path, coordmap: Dict[str, Any], values: Dict[str, Any]) -> Optional[bytes]:
    try:
        from pypdf import PdfReader, PdfWriter
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except Exception:
        return None
    try:
        # Build overlay PDF in-memory
        overlay_buf = BytesIO()
        c = canvas.Canvas(overlay_buf, pagesize=letter)
        for engine_key, spec in coordmap.items():
            if engine_key not in values:
                continue
            x = float(spec.get("x", 0))
            y = float(spec.get("y", 0))
            c.drawString(x, y, str(values[engine_key]))
        c.save()
        overlay_buf.seek(0)

        reader = PdfReader(str(template_pdf))
        overlay_reader = PdfReader(overlay_buf)
        writer = PdfWriter()
        for page_idx, page in enumerate(reader.pages):
            if page_idx < len(overlay_reader.pages):
                page.merge_page(overlay_reader.pages[page_idx])
            writer.add_page(page)
        out = BytesIO()
        writer.write(out)
        return out.getvalue()
    except Exception:
        return None


def _synthetic_pdf(jurisdiction: str, year: int, form_code: str, values: Dict[str, Any]) -> bytes:
    """Last-resort: render a one-page synthetic 'draft form' so users always
    get a downloadable artifact even when official templates are absent.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except Exception:
        # If reportlab is unavailable, emit a minimal valid PDF stub.
        body = f"% DRAFT {jurisdiction}/{year}/{form_code}\n" + "\n".join(
            f"{k}: {v}" for k, v in values.items()
        )
        return body.encode("utf-8")

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, 720, f"DRAFT — {jurisdiction} {form_code} ({year})")
    c.setFont("Helvetica", 10)
    c.drawString(72, 700, "This is a non-transmissible draft generated by WealthTax Agent.")
    c.drawString(72, 686, "NOT certified by CRA NETFILE or IRS MeF. For human review only.")
    c.setFont("Helvetica", 11)
    y = 650
    for key, value in values.items():
        line = f"{key}: {value}"
        c.drawString(72, y, line[:90])
        y -= 16
        if y < 72:
            c.showPage()
            y = 720
    c.save()
    return buf.getvalue()


def fill_form(jurisdiction: str, year: int, form_code: str, values: Dict[str, Any]) -> bytes:
    """Fill the official form for ``(jurisdiction, year, form_code)`` if a
    template exists; otherwise emit a synthetic draft PDF.
    """
    paths = _template_paths(jurisdiction, year, form_code)
    fieldmap = _load_yaml(paths["fieldmap"])
    coordmap = _load_yaml(paths["coordmap"])

    if paths["pdf"].exists() and fieldmap:
        data = _acroform_fill(paths["pdf"], fieldmap, values)
        if data:
            return data

    if paths["pdf"].exists() and coordmap:
        data = _text_overlay_fill(paths["pdf"], coordmap, values)
        if data:
            return data

    return _synthetic_pdf(jurisdiction, year, form_code, values)
